const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const core=require('../src/core.cjs');
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'photoflow-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const src=path.join(dir,'ảnh gốc.jpg');await fs.writeFile(src,'original image bytes');return {dir,src,dest:path.join(dir,'out','ảnh gốc.jpg')};}
test('Copy preserves original, content and modification time',async t=>{const {src,dest}=await fixture(t);const op=await core.transfer(src,dest);assert.equal(await core.hash(src),await core.hash(dest));assert.equal((await fs.stat(src)).size,(await fs.stat(dest)).size);assert.ok(Math.abs((await fs.stat(src)).mtimeMs-(await fs.stat(dest)).mtimeMs)<2);await core.undo(op);await assert.rejects(fs.stat(dest));assert.ok(await fs.stat(src));});
test('Move and undo restore original location',async t=>{const {src,dest}=await fixture(t);const op=await core.transfer(src,dest,true);await assert.rejects(fs.stat(src));await core.undo(op);assert.equal(await core.hash(src),op.hash);await assert.rejects(fs.stat(dest));});
test('Never overwrite an existing destination',async t=>{const {src,dest}=await fixture(t);await fs.mkdir(path.dirname(dest));await fs.writeFile(dest,'keep');await assert.rejects(core.transfer(src,dest,true));assert.equal(await fs.readFile(dest,'utf8'),'keep');assert.ok(await fs.stat(src));});
test('Concurrent destination collision permits only one transfer',async t=>{const {src,dest}=await fixture(t);const results=await Promise.allSettled([core.transfer(src,dest),core.transfer(src,dest)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(await core.hash(src),await core.hash(dest));});
test('Undo refuses modified destination',async t=>{const {src,dest}=await fixture(t);const op=await core.transfer(src,dest,true);await fs.writeFile(dest,'edited');await assert.rejects(core.undo(op));assert.equal(await fs.readFile(dest,'utf8'),'edited');});
test('Undo refuses occupied original path',async t=>{const {src,dest}=await fixture(t);const op=await core.transfer(src,dest,true);await fs.writeFile(src,'new photo');await assert.rejects(core.undo(op));assert.equal(await fs.readFile(src,'utf8'),'new photo');assert.ok(await fs.stat(dest));});
test('Reject same source, missing source, symlink source',async t=>{const {dir,src,dest}=await fixture(t);await assert.rejects(core.transfer(src,src,true));await assert.rejects(core.transfer(path.join(dir,'missing'),dest));if(process.platform!=='win32'){const link=path.join(dir,'link.jpg');await fs.symlink(src,link);await assert.rejects(core.transfer(link,dest));}});
test('Scan ignores links, distinguishes RAW and videos, respects recursion',async t=>{const {dir}=await fixture(t);await fs.mkdir(path.join(dir,'sub'));await fs.writeFile(path.join(dir,'sub','A.CR3'),'raw');await fs.writeFile(path.join(dir,'clip.MP4'),'video');await fs.writeFile(path.join(dir,'notes.txt'),'ignore');assert.equal((await core.scan(dir)).files.length,2);const deep=await core.scan(dir,true);assert.equal(deep.files.length,3);assert.ok(deep.files.some(f=>f.kind==='raw'));});
test('Windows invalid names and traversal rejected',()=>{for(const n of ['../a','a/b','a\\b','CON.jpg','aux','LPT1','a:bad','trailing.',' bad ','','..'])assert.throws(()=>core.validName(n));assert.equal(core.validName('Khách_Nguyễn_0001.jpg'),'Khách_Nguyễn_0001.jpg');});
test('CSV escapes quotes, commas, formulas and preserves Unicode',()=>{const out=core.csv([['=SUM(1)','a"b','ảnh,thẻ']]);assert.ok(out.includes('"\'=SUM(1)"'));assert.ok(out.includes('"a""b"'));assert.ok(out.includes('"ảnh,thẻ"'));});
