const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),Module=require('node:module');
test('Main IPC integration: live arrival, automatic student rename, numbering, no rename loop, folders',async t=>{
 const base=await fs.mkdtemp(path.join(process.env.TMPDIR||require('node:os').tmpdir(),'ipc-')),capture=path.join(base,'capture'),data=path.join(base,'data');await fs.mkdir(capture);await fs.mkdir(data);await fs.mkdir(path.join(capture,'Class A'));t.after(()=>fs.rm(base,{recursive:true,force:true}));
 const handlers={},timers=new Map(),sent=[];let win;class Window{constructor(){win=this;this.webContents={mainFrame:{},setWindowOpenHandler(){},on(){},send:(c,v)=>sent.push({c,v})};}setMenuBarVisibility(){}loadFile(){}on(){}isDestroyed(){return false;}}
 const electron={app:{whenReady:()=>Promise.resolve(),getPath:()=>data,getVersion:()=> '5.1.0',on(){},quit(){}},BrowserWindow:Window,ipcMain:{handle:(k,fn)=>handlers[k]=fn},dialog:{showOpenDialog:async()=>({canceled:false,filePaths:[capture]})},protocol:{registerSchemesAsPrivileged(){},handle(){}},session:{defaultSession:{setPermissionRequestHandler(){}}},nativeImage:{},shell:{},net:{}};
 const originalLoad=Module._load,interval=global.setInterval,now=Date.now;let clock=1000;Module._load=function(id,...args){return id==='electron'?electron:originalLoad.call(this,id,...args);};global.setInterval=(fn,ms)=>{timers.set(ms,fn);return ms;};Date.now=()=>clock;t.after(()=>{Module._load=originalLoad;global.setInterval=interval;Date.now=now;});require('../src/main.cjs');for(let i=0;i<50&&!handlers.live;i++)await new Promise(r=>setImmediate(r));assert.ok(handlers.live);
 const call=(name,...args)=>handlers[name]({sender:win.webContents,senderFrame:win.webContents.mainFrame},...args);const opened=await call('open',false);assert.equal(opened.folders.length,1);const prefs=await call('settings',{theme:'dark',target:2});assert.equal(prefs.theme,'dark');assert.equal(JSON.parse(await fs.readFile(path.join(data,'workspace.json'),'utf8')).settings.target,2);await call('destinationSet',2,{name:'Giao khách',folder:capture});assert.equal((await call('init')).destinationNames[2],'Giao khách');await assert.rejects(call('destinationSet',10,{name:'bad',folder:capture}));await assert.rejects(call('sourcePath','relative/path'));await call('cameraStart');assert.ok(sent.some(e=>e.c==='camera-status'&&!e.v.received));await call('student',{enabled:true,auto:true,id:'SV001',name:'Nguyễn An',next:10});await fs.writeFile(path.join(capture,'IMG_1.jpg'),Buffer.from([255,216,1,2,255,217]));await timers.get(750)();assert.equal(sent.filter(x=>x.c==='live-update').length,0);clock+=2000;await timers.get(750)();const event=sent.find(x=>x.c==='live-update');assert.ok(event);assert.ok(sent.some(e=>e.c==='camera-status'&&e.v.received));assert.equal(event.v.files[0].name,'SV001_Nguyễn_An_0010.jpg');assert.equal((await call('init')).student.next,11);await assert.rejects(fs.stat(path.join(capture,'IMG_1.jpg')));clock+=2000;await timers.get(750)();assert.equal(sent.filter(x=>x.c==='live-update').length,1);assert.equal((await call('init')).student.next,11);
 const child=await call('folder',path.join(capture,'Class A'));assert.equal(child.root,path.join(capture,'Class A'));const parent=await call('folder','..');assert.equal(parent.root,capture);await assert.rejects(call('folder',base));await call('live',{enabled:false,settleMs:1500});await fs.writeFile(path.join(capture,'IMG_2.jpg'),Buffer.from([255,216,255,217]));clock+=2000;await timers.get(750)();assert.equal(sent.filter(x=>x.c==='live-update').length,1);
});
