'use strict';
const fs=require('node:fs/promises'),{createReadStream}=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const images=new Set(['.jpg','.jpeg','.png','.webp','.gif','.bmp','.tif','.tiff','.heic','.heif','.avif']);
const raws=new Set(['.cr2','.cr3','.nef','.arw','.dng','.raf','.orf','.rw2']);
const videos=new Set(['.mp4','.mov','.m4v','.webm','.mkv','.avi','.mts']);
const kind=p=>images.has(path.extname(p).toLowerCase())?'image':raws.has(path.extname(p).toLowerCase())?'raw':videos.has(path.extname(p).toLowerCase())?'video':null;
function validName(n){if(typeof n!=='string'||!n.trim()||n.length>180||/[<>:"/\\|?*\x00-\x1f]/.test(n)||/[ .]$/.test(n)||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(\.|$)/i.test(n)||n==='.'||n==='..')throw Error('Tên tệp không hợp lệ trên Windows.');return n;}
async function hash(p){const h=crypto.createHash('sha256');for await(const b of createReadStream(p))h.update(b);return h.digest('hex');}
async function regular(p){const s=await fs.lstat(p);if(!s.isFile()||s.isSymbolicLink())throw Error('Chỉ xử lý tệp thường, không xử lý liên kết.');return s;}
async function scan(root,recursive=false){const out=[],warnings=[];async function walk(dir){let entries;try{entries=await fs.readdir(dir,{withFileTypes:true});}catch(e){warnings.push(`${dir}: ${e.message}`);return;}for(const d of entries){const p=path.join(dir,d.name);if(d.isSymbolicLink())continue;if(d.isDirectory()&&recursive)await walk(p);else if(d.isFile()&&kind(p)){try{const s=await fs.stat(p);out.push({path:p,name:d.name,kind:kind(p),size:s.size,mtime:s.mtimeMs});}catch(e){warnings.push(`${p}: ${e.message}`);}}}}await walk(root);out.sort((a,b)=>a.path.localeCompare(b.path,undefined,{numeric:true}));return {files:out,warnings};}
async function transfer(src,dest,move=false){const before=await regular(src);if(path.resolve(src)===path.resolve(dest))throw Error('Nguồn và đích trùng nhau.');await fs.mkdir(path.dirname(dest),{recursive:true});let handle;try{handle=await fs.open(dest,'wx');await handle.close();}catch(e){if(e.code==='EEXIST')throw Error('Tên đã tồn tại ở đích; không ghi đè.');throw e;}let digest;try{await fs.copyFile(src,dest);digest=await hash(dest);if(digest!==await hash(src))throw Error('Bản sao không khớp; giữ nguyên nguồn.');const after=await regular(src);if(before.size!==after.size||before.mtimeMs!==after.mtimeMs)throw Error('Nguồn thay đổi trong khi sao chép.');await fs.utimes(dest,before.atime,before.mtime);const f=await fs.open(dest,'r+');try{await f.sync();}finally{await f.close();}}catch(e){await fs.unlink(dest).catch(()=>{});throw e;}if(move){try{await fs.unlink(src);}catch(e){throw Error(`Đã sao chép nhưng chưa xóa nguồn: ${e.message}`);}}return {src,dest,move,hash:digest};}
async function undo(op){await regular(op.dest);if(await hash(op.dest)!==op.hash)throw Error('Tệp đích đã thay đổi; không thể hoàn tác an toàn.');if(op.move)return transfer(op.dest,op.src,true);await fs.unlink(op.dest);}
function csv(rows){const cell=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@-]/,"'$&")+'"';return '\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n');}
module.exports={kind,validName,hash,regular,scan,transfer,undo,csv};
