'use strict';
const {app,BrowserWindow,ipcMain,dialog,protocol,net,shell,nativeImage,session}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url'),{execFile}=require('node:child_process'),{promisify}=require('node:util'),crypto=require('node:crypto');
const core=require('./core.cjs');const config=require('./config.cjs');let cameraTest=null;const {ArrivalTracker,readable,studentStem}=require('./live.cjs');const tracker=new ArrivalTracker();let recursive=false,liveEnabled=true,liveRunning=null,revision=0,libraryRoot='',folderOptions=[],lastLiveStatus='';const mediaUrls=new Map();const run=promisify(execFile);let win,root='',files=[],allowed=new Set(),destinations=[],state={marks:{},destinations:[]},undoStack=[],busy=false,stateFile;const tokens=new Map(),thumbs=new Map();
protocol.registerSchemesAsPrivileged([{scheme:'media',privileges:{standard:true,secure:true,supportFetchAPI:true,stream:true,corsEnabled:true}}]);
function url(p){const id=crypto.randomUUID();tokens.set(id,p);return 'media://file/'+id;}
async function save(){const temp=stateFile+'.tmp';await fs.writeFile(temp,JSON.stringify(state));await fs.rename(temp,stateFile);}
function send(c,v){if(win&&!win.isDestroyed())win.webContents.send(c,v);}
function expose(f){let cached=mediaUrls.get(f.path);const sig=`${f.size}:${f.mtime}`;if(!cached||cached.sig!==sig){if(cached)tokens.delete(cached.url.split('/').at(-1));cached={sig,url:url(f.path)};mediaUrls.set(f.path,cached);thumbs.delete(f.path);}return {...f,url:cached.url,mark:state.marks[f.path]||{}};}
function snapshot(extra={}){const active=new Set(files.map(f=>f.path));for(const [p,v] of mediaUrls)if(!active.has(p)){tokens.delete(v.url.split('/').at(-1));mediaUrls.delete(p);thumbs.delete(p);}return {root,revision,files:files.map(expose),warnings:[],folders:folderOptions,libraryRoot,recents:state.recents||[],...extra};}
async function folders(){folderOptions=[];for(const d of await fs.readdir(root,{withFileTypes:true}).catch(()=>[]))if(d.isDirectory()&&!d.isSymbolicLink())folderOptions.push({name:d.name,path:path.join(root,d.name)});folderOptions.sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));}
async function refresh(rec=recursive){recursive=!!rec;if(!root)return {files:[],warnings:[]};const result=await core.scan(root,recursive);files=result.files;allowed=new Set(files.map(f=>f.path));tracker.seed(files);revision++;await folders();return snapshot({warnings:result.warnings});}
function liveStatus(message,pending=0){const key=message+pending;if(key!==lastLiveStatus){lastLiveStatus=key;send('live-status',{message,pending});}}
async function renameStudents(paths,settings){const results=[];for(const src of paths){try{check(src);if(core.kind(src)!=='image'&&core.kind(src)!=='raw')throw Error('Chế độ sinh viên chỉ đổi tên ảnh.');const dest=path.join(path.dirname(src),studentStem(settings,settings.next)+path.extname(src));const op=await core.transfer(src,dest,true);undoStack.push(op);if(state.marks[src]){state.marks[dest]=state.marks[src];delete state.marks[src];}settings.next++;await save();const stat=await fs.stat(dest);const file={path:dest,name:path.basename(dest),kind:core.kind(dest),size:stat.size,mtime:stat.mtimeMs};files=files.filter(f=>f.path!==src);files.push(file);allowed.delete(src);allowed.add(dest);tracker.published.delete(src);tracker.pending.delete(src);tracker.commit(file);results.push({src,dest,ok:true,file});}catch(e){results.push({src,ok:false,error:e.message});}}return results;}
async function pollLive(){if(!liveEnabled||!root||busy)return;const scanRoot=root;const result=await core.scan(scanRoot,recursive);if(busy||scanRoot!==root)return;if(result.warnings.length){liveStatus('Thư mục chưa truy cập được; đang chờ kết nối lại.');return;}const delta=tracker.observe(result.files,Date.now());const ready=[];for(const f of delta.ready)if(await readable(f))ready.push(f);if(busy||scanRoot!==root)return;busy=true;try{let changes=[];const removed=new Set(delta.removed);for(const p of removed)tracker.published.delete(p);files=files.filter(f=>!removed.has(f.path));for(const f of ready){files=files.filter(old=>old.path!==f.path);files.push(f);tracker.commit(f);changes.push(f.path);if(cameraTest&&cameraTest.root===root&&!cameraTest.paths.has(f.path)){send('camera-status',{message:'Đã nhận tệp mới: '+f.name,received:true});cameraTest=null;}}allowed=new Set(files.map(f=>f.path));if(changes.length&&state.student?.enabled&&state.student?.auto){const photos=changes.filter(p=>['image','raw'].includes(core.kind(p)));const renamed=await renameStudents(photos,state.student);changes=changes.map(p=>renamed.find(r=>r.src===p&&r.ok)?.dest||p);const failed=renamed.filter(r=>!r.ok);if(failed.length)send('student-error',failed.map(r=>r.error).join(' | '));send('student-settings',state.student);}const beforeFolders=JSON.stringify(folderOptions);await folders();if(changes.length||removed.size||beforeFolders!==JSON.stringify(folderOptions)){revision++;send('live-update',snapshot({changes}));}liveStatus('Đang theo dõi thư mục',tracker.pending.size);}finally{busy=false;}}

function check(p){if(!allowed.has(p))throw Error('Tệp không thuộc thư mục đang mở.');return p;}
async function drives(){if(process.platform==='win32'){const {stdout}=await run('powershell.exe',['-NoProfile','-NonInteractive','-Command',"Get-CimInstance Win32_LogicalDisk | Select-Object DeviceID,VolumeName,DriveType,FreeSpace,Size | ConvertTo-Json -Compress"],{timeout:8000,windowsHide:true});const data=JSON.parse(stdout||'[]');return (Array.isArray(data)?data:[data]).map(d=>({path:d.DeviceID+'\\',name:d.VolumeName||d.DeviceID,removable:d.DriveType===2,free:d.FreeSpace}));}const found=[];for(const base of process.platform==='darwin'?['/Volumes']:['/media/'+require('node:os').userInfo().username,'/mnt']){for(const name of await fs.readdir(base).catch(()=>[]))found.push({path:path.join(base,name),name,removable:true});}return found;}
function handle(channel,fn,lock=false){ipcMain.handle(channel,async(e,...args)=>{if(e.sender!==win.webContents||e.senderFrame!==win.webContents.mainFrame)throw Error('Yêu cầu không hợp lệ.');if(lock&&busy)throw Error('Đang xử lý, vui lòng chờ.');if(lock)busy=true;try{if(lock&&liveRunning)await liveRunning;return await fn(...args);}finally{if(lock)busy=false;}});}
app.whenReady().then(async()=>{stateFile=path.join(app.getPath('userData'),'workspace.json');try{state=JSON.parse(await fs.readFile(stateFile,'utf8'));}catch{}state.marks||={};if(state.student)state.student.auto=false;try{state.settings=config.settings(state.settings);}catch{state.settings={...config.defaults};}state.destinationNames=Array.isArray(state.destinationNames)?state.destinationNames:[];state.recents=Array.isArray(state.recents)?state.recents:[];liveEnabled=state.settings.liveEnabled;recursive=state.settings.recursive;tracker.settleMs=state.settings.settleMs;destinations=state.destinations||[];
protocol.handle('media',async request=>{const p=tokens.get(new URL(request.url).pathname.slice(1));if(!p)return new Response('Not found',{status:404});try{await core.regular(p);const response=await net.fetch(pathToFileURL(p).href,{headers:request.headers});const headers=new Headers(response.headers);headers.set('Access-Control-Allow-Origin','*');return new Response(response.body,{status:response.status,headers});}catch{return new Response('Unavailable',{status:404});}});
session.defaultSession.setPermissionRequestHandler((_w,_p,cb)=>cb(false));
win=new BrowserWindow({width:1500,height:940,minWidth:1100,minHeight:720,backgroundColor:'#f4f6fa',title:'PhotoFlow Studio',webPreferences:{preload:path.join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});win.setMenuBarVisibility(false);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.loadFile(path.join(__dirname,'index.html'));
handle('init',()=>({destinations,destinationNames:state.destinationNames,recents:state.recents,settings:state.settings,brands:config.brands,version:app.getVersion(),student:state.student||{enabled:false,auto:false,id:'',name:'',next:1},liveEnabled}));
handle('open',async(rec=false,drive)=>{if(drive){if(!(await drives()).some(d=>d.path===drive))throw Error('Ổ đĩa đã ngắt kết nối.');root=drive;}else{const r=await dialog.showOpenDialog(win,{properties:['openDirectory']});if(r.canceled)return null;root=r.filePaths[0];}root=await fs.realpath(root);libraryRoot=root;cameraTest=null;state.recents=[root,...state.recents.filter(p=>p!==root)].slice(0,8);await save();return refresh(rec);},true);
handle('refresh',refresh,true);
handle('folder',async(target)=>{if(target==='..'){if(root===libraryRoot)return snapshot();root=path.dirname(root);}else {const chosen=folderOptions.find(f=>f.path===target);if(!chosen)throw Error('Chọn thư mục con trong danh sách.');const real=await fs.realpath(chosen.path),base=await fs.realpath(libraryRoot),rel=path.relative(base,real);if(rel.startsWith('..')||path.isAbsolute(rel))throw Error('Thư mục nằm ngoài bộ ảnh.');root=real;}return refresh();},true);
handle('live',async(settings)=>{if(typeof settings.enabled!=='boolean'||![1500,3000,5000].includes(settings.settleMs))throw Error('Cấu hình theo dõi không hợp lệ.');liveEnabled=settings.enabled;tracker.settleMs=settings.settleMs;state.settings.liveEnabled=liveEnabled;state.settings.settleMs=settings.settleMs;await save();liveStatus(liveEnabled?'Đang theo dõi thư mục':'Đã tắt cập nhật tự động');return {enabled:liveEnabled};},true);
handle('student',async(settings)=>{if(typeof settings.enabled!=='boolean'||typeof settings.auto!=='boolean')throw Error('Cấu hình ảnh thẻ không hợp lệ');if(settings.enabled)studentStem(settings,settings.next);state.student={enabled:settings.enabled,auto:settings.auto,id:String(settings.id||''),name:String(settings.name||''),next:settings.next};await save();return state.student;},true);
handle('studentRename',async(paths)=>{if(!state.student?.enabled)throw Error('Bật và lưu chế độ ảnh thẻ sinh viên trước.');paths=[...new Set(paths)];paths.forEach(check);const result=await renameStudents(paths,state.student);send('student-settings',state.student);revision++;return {results:result,snapshot:snapshot()};},true);
handle('drives',drives);
handle('destination',async(index)=>{if(!Number.isInteger(index)||index<0||index>9)throw Error('Đích không hợp lệ');const r=await dialog.showOpenDialog(win,{properties:['openDirectory','createDirectory']});if(!r.canceled){destinations[index]=r.filePaths[0];state.destinations=destinations;await save();}return destinations;},true);
handle('settings',async(patch)=>{state.settings=config.settings({...state.settings,...patch});liveEnabled=state.settings.liveEnabled;tracker.settleMs=state.settings.settleMs;await save();return state.settings;},true);
handle('sourcePath',async(value,rec=false)=>{if(typeof value!=='string'||!path.isAbsolute(value.trim()))throw Error('Nhập đường dẫn thư mục đầy đủ.');const folder=await fs.realpath(value.trim());if(!(await fs.stat(folder)).isDirectory())throw Error('Đây không phải thư mục.');root=folder;libraryRoot=root;cameraTest=null;state.recents=[root,...state.recents.filter(p=>p!==root)].slice(0,8);await save();return refresh(rec);},true);
handle('destinationSet',async(index,{name,folder})=>{if(!Number.isInteger(index)||index<0||index>9||typeof name!=='string'||name.trim().length>40||typeof folder!=='string')throw Error('Thông tin thư mục đích không hợp lệ.');let real='';if(folder.trim()){if(!path.isAbsolute(folder.trim()))throw Error('Nhập đường dẫn đầy đủ.');real=await fs.realpath(folder.trim());if(!(await fs.stat(real)).isDirectory())throw Error('Đích phải là thư mục.');await fs.access(real,require('node:fs').constants.W_OK);}destinations[index]=real;state.destinations=destinations;state.destinationNames[index]=name.trim();await save();return {destinations,names:state.destinationNames};},true);
handle('openFolder',async(which,index)=>{const folder=which==='source'?root:which==='destination'?destinations[index]:null;if(!folder)throw Error('Chưa chọn thư mục.');const error=await shell.openPath(folder);if(error)throw Error(error);});
handle('cameraScan',async()=>{if(process.platform!=='win32')return {devices:[],message:'Nhận diện thiết bị chỉ có trên Windows. Chế độ thư mục vẫn sử dụng được.'};try{const {stdout}=await run('powershell.exe',['-NoProfile','-NonInteractive','-Command',"[Console]::OutputEncoding=[System.Text.Encoding]::UTF8; Get-CimInstance Win32_PnPEntity | Where-Object { $_.Present -eq $true -and ($_.PNPClass -in @('Camera','Image','WPD') -or $_.Name -match '(Canon.*EOS|Nikon|Sony.*(Camera|ILCE)|FUJIFILM|LUMIX|OM Digital)') } | Select-Object Name,PNPClass,Status | ConvertTo-Json -Compress"],{timeout:10000,windowsHide:true,maxBuffer:1024*1024});return {devices:config.deviceList(stdout),message:'Thiết bị do Windows nhận diện; không xác nhận khả năng chụp từ xa.'};}catch(e){return {devices:[],message:'Không quét được thiết bị: '+e.message+'. Bạn vẫn có thể chọn thư mục nhận ảnh.'};}});
handle('cameraGuide',async(brand)=>{const item=config.brands[brand];if(!item?.url)throw Error('Hãy xem hướng dẫn từ nhà sản xuất model đang sử dụng.');await shell.openExternal(item.url);});
handle('cameraStart',async()=>{if(!root)throw Error('Chọn thư mục nhận ảnh trước.');await fs.access(root);liveEnabled=true;state.settings.liveEnabled=true;await save();cameraTest={root,paths:new Set(files.map(f=>f.path))};lastLiveStatus='';send('camera-status',{message:'Đang chờ ảnh mới. Hãy chụp thử bằng máy ảnh hoặc phần mềm hãng.',received:false});return {root};},true);
handle('cameraStop',async()=>{cameraTest=null;liveEnabled=false;state.settings.liveEnabled=false;await save();send('camera-status',{message:'Đã dừng nhận ảnh trong PhotoFlow. Máy ảnh vẫn do phần mềm hãng quản lý.',received:false});},true);
handle('mark',async(paths,mark)=>{if(![undefined,'pick','reject',''].includes(mark.flag)||![undefined,0,1,2,3,4,5].includes(mark.stars))throw Error('Nhãn không hợp lệ');for(const p of paths){check(p);state.marks[p]={...state.marks[p],...mark};}await save();},true);
handle('thumbnail',async(p)=>{check(p);if(thumbs.has(p))return thumbs.get(p);if(core.kind(p)!=='image')return null;try{const img=await nativeImage.createThumbnailFromPath(p,{width:220,height:150});const data=img.toDataURL();if(thumbs.size>350)thumbs.delete(thumbs.keys().next().value);thumbs.set(p,data);return data;}catch{return null;}});
handle('operate',async({paths,mode,index,prefix,start=1})=>{if(!['copy','move','rename'].includes(mode))throw Error('Thao tác sai');paths=[...new Set(paths)];paths.forEach(check);if(!paths.length)return [];const target=destinations[index];if(mode!=='rename'&&!target)throw Error('Chọn thư mục đích trước.');if(mode==='rename')core.validName(prefix);if(!Number.isInteger(start)||start<0)throw Error('Số bắt đầu không hợp lệ');if(mode==='move'){const r=await dialog.showMessageBox(win,{type:'question',buttons:['Hủy','Di chuyển'],defaultId:0,cancelId:0,message:`Di chuyển ${paths.length} tệp?`,detail:'Kiểm tra SHA-256 bản sao trước khi xóa nguồn. Có thể hoàn tác trong phiên này.'});if(r.response!==1)return [];}
const results=[];for(let i=0;i<paths.length;i++){const src=paths[i];try{const name=mode==='rename'?(paths.length===1?prefix:prefix+'_'+String(start+i).padStart(4,'0'))+path.extname(src):path.basename(src);core.validName(name);const dest=path.join(mode==='rename'?path.dirname(src):target,name);const op=await core.transfer(src,dest,mode!=='copy');undoStack.push(op);if(state.marks[src]){state.marks[dest]=state.marks[src];if(op.move)delete state.marks[src];}results.push({src,dest,ok:true});}catch(e){results.push({src,ok:false,error:e.message});}send('progress',{done:i+1,total:paths.length});}await save();return results;},true);
handle('undo',async()=>{const op=undoStack.at(-1);if(!op)throw Error('Chưa có thao tác để hoàn tác.');await core.undo(op);undoStack.pop();if(op.move&&state.marks[op.dest]){state.marks[op.src]=state.marks[op.dest];delete state.marks[op.dest];await save();}return true;},true);
handle('duplicates',async()=>{const groups=new Map(),same=[];for(const f of files){const list=groups.get(f.size)||[];list.push(f);groups.set(f.size,list);}let n=0;for(const group of groups.values()){if(group.length<2)continue;const hashes=new Map();for(const f of group){try{const h=await core.hash(f.path);const list=hashes.get(h)||[];list.push(f.path);hashes.set(h,list);}catch{}send('progress',{done:++n,total:files.length});}for(const list of hashes.values())if(list.length>1)same.push(list);}return same;},true);
handle('reveal',p=>shell.showItemInFolder(check(p)));
handle('report',async()=>{const r=await dialog.showSaveDialog(win,{defaultPath:'PhotoFlow-danh-sach.csv',filters:[{name:'CSV',extensions:['csv']}]});if(r.canceled)return;await fs.writeFile(r.filePath,core.csv([['Tên','Đường dẫn','Loại','Byte','Chọn/Loại','Sao'],...files.map(f=>[f.name,f.path,f.kind,f.size,state.marks[f.path]?.flag,state.marks[f.path]?.stars])]));return r.filePath;},true);
handle('export',async(data)=>{if(typeof data!=='string'||!data.startsWith('data:image/jpeg;base64,')||data.length>80e6)throw Error('Dữ liệu xuất không hợp lệ');const r=await dialog.showSaveDialog(win,{defaultPath:'PhotoFlow-anh-the.jpg',filters:[{name:'JPEG',extensions:['jpg']}]});if(r.canceled)return null;await fs.writeFile(r.filePath,Buffer.from(data.split(',')[1],'base64'));return r.filePath;},true);
let polling=false;const timer=setInterval(async()=>{if(polling)return;polling=true;try{send('drives',await drives());}catch(e){send('drive-error',e.message);}finally{polling=false;}},3000);const liveTimer=setInterval(()=>{if(liveRunning)return;liveRunning=pollLive().catch(e=>liveStatus('Theo dõi tạm lỗi: '+e.message)).finally(()=>{liveRunning=null;});return liveRunning;},750);win.on('closed',()=>{clearInterval(timer);clearInterval(liveTimer);});
});app.on('window-all-closed',()=>app.quit());
