'use strict';
function applyPreferences(initial=true){document.body.classList.toggle('light',(appSettings.theme||'light')==='light');if(initial){$('liveEnabled').checked=appSettings.liveEnabled!==false;$('settleMs').value=String(appSettings.settleMs||1500);$('followLatest').checked=appSettings.followLatest!==false;$('recursive').checked=!!appSettings.recursive;$('target').value=String(appSettings.target||0);}}
function openSource(){populateRecents();$('sourcePathInput').value=activeRoot;$('sourceDialog').showModal();}
function populateRecents(){$('recentFolders').replaceChildren();for(const folder of recentPaths){const b=document.createElement('button');b.textContent=folder;b.onclick=()=>task(async()=>{const result=await api.sourcePath(folder,$('recursive').checked);$('sourceDialog').close();await load(result);});$('recentFolders').append(b);}if(!recentPaths.length)$('recentFolders').textContent='Chưa có thư mục gần đây.';}
$('sourceOpen').onclick=openSource;$('sourceUse').onclick=()=>task(async()=>{const result=await api.sourcePath($('sourcePathInput').value,$('recursive').checked);$('sourceDialog').close();await load(result);});$('sourceBrowse').onclick=()=>task(async()=>{const result=await api.open($('recursive').checked);if(result){$('sourceDialog').close();await load(result);}});
$('emptyOpen').onclick=()=>$('open').click();$('emptyCamera').onclick=()=>openCamera();
$('target').onchange=()=>{destinationsUI();task(async()=>{appSettings=await api.settings({target:+$('target').value});});};
$('targetBrowse').onclick=()=>task(async()=>{destinations=await api.destination(+$('target').value);destinationsUI();});$('targetReveal').onclick=()=>task(()=>api.openFolder('destination',+$('target').value));
function renderDestinationEditor(){$('destinationEditor').replaceChildren();for(let i=0;i<10;i++){const row=document.createElement('section');row.className='destination-row';const name=document.createElement('input');name.value=destinationNames[i]||$('target').options[i]?.text||'Đích '+(i+1);name.maxLength=40;name.setAttribute('aria-label','Tên đích '+(i+1));const folder=document.createElement('input');folder.value=destinations[i]||'';folder.placeholder='Chưa chọn đường dẫn';folder.setAttribute('aria-label','Đường dẫn đích '+(i+1));const browse=document.createElement('button');browse.textContent='Duyệt…';browse.onclick=()=>task(async()=>{destinations=await api.destination(i);folder.value=destinations[i]||'';destinationsUI();});const actions=document.createElement('div');actions.className='row-actions';const save=document.createElement('button');save.textContent='Lưu tên & đường dẫn';save.onclick=()=>task(async()=>{const r=await api.destinationSet(i,{name:name.value,folder:folder.value});destinations=r.destinations;destinationNames=r.names;destinationsUI();status('Đã lưu thư mục đích '+(i+1));});const use=document.createElement('button');use.textContent='Dùng đích này';use.onclick=()=>task(async()=>{const r=await api.destinationSet(i,{name:name.value,folder:folder.value});if(!r.destinations[i])throw Error('Chọn đường dẫn trước.');destinations=r.destinations;destinationNames=r.names;appSettings=await api.settings({target:i});$('target').value=String(i);destinationsUI();$('destinationsDialog').close();});const clear=document.createElement('button');clear.textContent='Bỏ đường dẫn';clear.onclick=()=>task(async()=>{const r=await api.destinationSet(i,{name:name.value,folder:''});destinations=r.destinations;destinationNames=r.names;folder.value='';destinationsUI();status('Đã bỏ cấu hình đường dẫn; không xóa thư mục hay ảnh.');});actions.append(save,use,clear);row.append(name,folder,browse,actions);$('destinationEditor').append(row);}}
$('destinationsOpen').onclick=()=>{renderDestinationEditor();$('destinationsDialog').showModal();};
function fillSettings(value){$('settingTheme').value=value.theme||'light';$('settingSettle').value=String(value.settleMs||1500);$('settingLive').checked=value.liveEnabled!==false;$('settingFollow').checked=value.followLatest!==false;$('settingRecursive').checked=!!value.recursive;}
$('settingsOpen').onclick=()=>{fillSettings(appSettings);$('settingsDialog').showModal();};$('settingsReset').onclick=()=>fillSettings({});$('settingsSave').onclick=()=>task(async()=>{const previousRecursive=$('recursive').checked;appSettings=await api.settings({theme:$('settingTheme').value,settleMs:+$('settingSettle').value,liveEnabled:$('settingLive').checked,followLatest:$('settingFollow').checked,recursive:$('settingRecursive').checked,target:+$('target').value});applyPreferences();$('settingsDialog').close();if(activeRoot&&previousRecursive!==appSettings.recursive)await load(await api.refresh(appSettings.recursive));status('Đã lưu cài đặt ứng dụng.');});
$('helpOpen').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
function openCamera(){$('cameraBrand').replaceChildren();for(const [key,brand] of Object.entries(brandCatalog))$('cameraBrand').add(new Option(brand.name,key));$('cameraFolder').textContent=activeRoot||'Chưa chọn thư mục';cameraInstructions();$('cameraDialog').showModal();}
function cameraInstructions(){const brand=brandCatalog[$('cameraBrand').value],method=$('cameraMethod').value;$('cameraGuide').disabled=!brand?.url;$('cameraInstructions').textContent=method==='card'?'Chọn thư mục DCIM hoặc thư mục ảnh trên thẻ nhớ/ổ đĩa. Không điều khiển chụp bằng chế độ này.':method==='wifi'?`Dùng ${brand?.app||'phần mềm tương thích'} hoặc luồng truyền ảnh đã thiết lập để lưu ảnh vào thư mục máy tính. Chỉ những model hỗ trợ mới truyền được qua Wi-Fi/LAN.`:`Kết nối cáp dữ liệu và thiết lập ${brand?.app||'phần mềm tương thích'} để lưu ảnh vào máy tính. Chọn đúng chế độ USB theo hướng dẫn model.`;}
$('cameraOpen').onclick=openCamera;$('cameraBrand').onchange=cameraInstructions;$('cameraMethod').onchange=cameraInstructions;$('cameraGuide').onclick=()=>task(()=>api.cameraGuide($('cameraBrand').value));$('cameraFolderPick').onclick=()=>task(async()=>{const r=await api.open($('recursive').checked);if(r){await load(r);$('cameraTestStatus').textContent='Đã chọn thư mục. Chưa xác nhận nhận ảnh.';}});
$('cameraScan').onclick=async()=>{const b=$('cameraScan');b.disabled=true;$('cameraDevices').textContent='Đang quét thiết bị…';try{const r=await api.cameraScan();$('cameraDevices').replaceChildren();for(const d of r.devices){const p=document.createElement('p');p.textContent=d.name+' · '+d.status;$('cameraDevices').append(p);}const p=document.createElement('p');p.textContent=r.devices.length?r.message:'Chưa tìm thấy thiết bị ảnh qua Windows. '+r.message;$('cameraDevices').append(p);}catch(e){$('cameraDevices').textContent=e.message;}finally{b.disabled=false;}};
$('cameraStart').onclick=()=>task(async()=>{await api.cameraStart();$('liveEnabled').checked=true;appSettings.liveEnabled=true;$('followLatest').checked=true;status('Hãy chụp thử; app đang chờ tệp mới.');});$('cameraStop').onclick=()=>task(async()=>{await api.cameraStop();$('liveEnabled').checked=false;appSettings.liveEnabled=false;});api.on('camera-status',info=>{$('cameraTestStatus').textContent=info.message;if(info.received)status(info.message);});

initializeApp();
